// ============================================================
// templates/integration.js — worked example (data only): Enterprise Integration Strategy
// Structure follows the Integration Reference Architecture at itarchitecturepatterns.net.
// Self-registers into window.STRATEGY_TEMPLATES.
// ============================================================

window.STRATEGY_TEMPLATES = window.STRATEGY_TEMPLATES || [];
window.STRATEGY_TEMPLATES.push({
  id: "integration",
  name: "Integration Strategy (example)",
  description: "Enterprise integration: Consumers, a rich Integration layer (API management, ESB, ETL, CDC, MDM, SFT, event streaming, workflow, AI) and Producers, plus cross-cutting Information, Governance, Security, Monitoring and Dev/Test layers.",
  source: "Integration Reference Architecture",
  sourceUrl: "https://itarchitecturepatterns.net/reference-architectures/integration-refence-architecture",
  data: {
    schemaVersion: 1,
    meta: {
      title: "Example: Enterprise Integration Strategy",
      organisation: "Example Organisation",
      author: "",
    },
    statuses: [
      { id: "strategic",    name: "Strategic",    color: "#16a34a", description: "Invest and grow — the target state.", order: 1 },
      { id: "emerging",     name: "Emerging",     color: "#7c3aed", description: "Under evaluation / pilot.", order: 2 },
      { id: "tactical",     name: "Tactical",     color: "#f59e0b", description: "Acceptable for now; not the target.", order: 3 },
      { id: "contain",      name: "Contain",      color: "#64748b", description: "No new investment or workloads.", order: 4 },
      { id: "decommission", name: "Decommission", color: "#dc2626", description: "Actively exiting.", order: 5 },
    ],
    users: [
      { id: "iu-integration-dev", icon: "code", name: "Integration Developer", type: "primary",
        description: "Builds and maintains APIs, flows, event pipelines and connectors across systems.",
        goals: ["Reusable integration patterns", "Fast, safe deployment", "Good local testing and mocking"],
        painPoints: ["Point-to-point spaghetti", "Undocumented legacy interfaces", "Slow manual releases"] },
      { id: "iu-api-owner", icon: "package", name: "API Product Owner", type: "primary",
        description: "Owns API products end to end: their contracts, versions, consumers and adoption.",
        goals: ["Well-documented, versioned APIs", "Self-service onboarding", "Clear usage analytics"],
        painPoints: ["Breaking changes surprising consumers", "No visibility of who uses what"] },
      { id: "iu-enterprise-architect", icon: "compass", name: "Enterprise Architect", type: "secondary",
        description: "Sets integration standards and steers the move off legacy middleware.",
        goals: ["Consistent standards across teams", "A clear target-state platform", "Reduced vendor sprawl"],
        painPoints: ["Multiple overlapping ESB/iPaaS tools", "No single source of interface truth"] },
      { id: "iu-platform-ops", icon: "settings", name: "Platform Operations", type: "secondary",
        description: "Runs, scales and monitors the integration runtime; first responder to incidents.",
        goals: ["Reliable, observable runtimes", "Automated scaling and recovery"],
        painPoints: ["Silent message failures", "Hard-to-trace cross-system flows"] },
      { id: "iu-security-engineer", icon: "shield", name: "Security Engineer", type: "secondary",
        description: "Secures APIs and integration flows: authentication, authorisation, secrets and policy.",
        goals: ["Consistent OAuth/OIDC everywhere", "Central secret and certificate management"],
        painPoints: ["Inconsistent auth per team", "Credentials in config files"] },
      { id: "iu-partner", icon: "handshake", name: "External Partner / Consumer", type: "external",
        description: "Partners and third parties that consume APIs or exchange B2B messages.",
        goals: ["Stable, documented APIs", "Secure self-service access", "Reliable B2B exchange"],
        painPoints: ["Ad-hoc file drops", "No SLAs or change notice"] },
    ],
    useCases: [
      { id: "iuc-realtime-api", icon: "plug", name: "Real-Time API Integration",
        description: "Expose and consume synchronous REST/GraphQL APIs between applications and partners.",
        businessValue: "Real-time experiences and decoupled applications." },
      { id: "iuc-event-driven", icon: "waves", name: "Event-Driven Integration",
        description: "Publish and subscribe to business events for loosely-coupled, reactive processing.",
        businessValue: "React in seconds and scale services independently." },
      { id: "iuc-batch-file", icon: "upload", name: "Batch & File Integration",
        description: "Scheduled batch, CDC and managed file transfer with transformation between systems.",
        businessValue: "Reliable movement of bulk and legacy data." },
      { id: "iuc-b2b-partner", icon: "handshake", name: "B2B / Partner Integration",
        description: "Exchange API and file-based transactions securely with external partners.",
        businessValue: "Automated, auditable partner trading." },
      { id: "iuc-legacy-modernisation", icon: "refresh-cw", name: "Legacy Modernisation",
        description: "Wrap and gradually replace legacy middleware with modern APIs and events.",
        businessValue: "Lower risk and cost; retire ageing platforms." },
      { id: "iuc-self-service-api", icon: "book-open", name: "Self-Service API Consumption",
        description: "Developers discover, subscribe to and consume governed API products via a catalogue.",
        businessValue: "Faster delivery; less integration backlog." },
    ],
    layers: [
      { id: "il-consumers",  name: "Consumers",  color: "slate",  order: 1, orientation: "vertical",
        description: "End users and systems that consume services and data through integration." },
      { id: "il-integration", name: "Integration", color: "blue", order: 2, orientation: "vertical",
        description: "Core connectivity and data-movement capabilities that mediate between consumers and producers." },
      { id: "il-producers",  name: "Producers",  color: "cyan",   order: 3, orientation: "vertical",
        description: "The origin systems and sources of data and services being integrated." },
      { id: "il-information", name: "Information", color: "purple", order: 4, orientation: "cross-cutting",
        description: "Data modelling and shared vocabulary that standardise meaning across integrations." },
      { id: "il-governance", name: "Governance", color: "green",  order: 5, orientation: "cross-cutting",
        description: "Service lifecycle, discovery and registry management across the estate." },
      { id: "il-security",   name: "Security",   color: "rose",   order: 6, orientation: "cross-cutting",
        description: "Access control and data protection across every layer." },
      { id: "il-management", name: "Management & Monitoring", color: "amber", order: 7, orientation: "cross-cutting",
        description: "Runtime operations, observability and scheduling across every layer." },
      { id: "il-devtest",    name: "Development & Testing Tools", color: "lime", order: 8, orientation: "cross-cutting",
        description: "Engineering and quality-assurance capabilities that build and deliver integrations." },
    ],
    components: [
      // --- Consumers ---
      { id: "c-cons-internal", layerId: "il-consumers", row: 1, icon: "server",    name: "Internal IT Systems",
        description: "Internal applications consuming services and data via integration." },
      { id: "c-cons-external", layerId: "il-consumers", row: 1, icon: "box",       name: "External IT Systems",
        description: "Third-party systems consuming published services." },
      { id: "c-cons-partners", layerId: "il-consumers", row: 1, icon: "handshake", name: "External Partners",
        description: "Trading partners consuming APIs and B2B exchanges." },
      { id: "c-cons-web",      layerId: "il-consumers", row: 2, icon: "globe",     name: "Web Sites",
        description: "Public and internal web channels consuming integration services." },
      { id: "c-cons-mobile",   layerId: "il-consumers", row: 2, icon: "monitor",   name: "Mobile Devices",
        description: "Mobile clients consuming APIs and events." },
      { id: "c-cons-field",    layerId: "il-consumers", row: 2, icon: "cpu",       name: "Field Devices",
        description: "IoT and field devices consuming and emitting data." },

      // --- Integration ---
      { id: "c-int-api-mgmt",   layerId: "il-integration", row: 1, icon: "plug",      name: "API Management",
        description: "Create, document, publish, secure, monitor and govern APIs." },
      { id: "c-int-middleware", layerId: "il-integration", row: 1, icon: "network",   name: "Middleware Services (ESB)",
        description: "Message routing, protocol translation and data transformation." },
      { id: "c-int-esp",        layerId: "il-integration", row: 1, icon: "waves",     name: "Event Stream Processing (ESP)",
        description: "Real-time event computation and analytics over streams." },
      { id: "c-int-workflow",   layerId: "il-integration", row: 1, icon: "workflow",  name: "Workflow (BPM / BRMS)",
        description: "Business process orchestration and rules automation." },
      { id: "c-int-etl",        layerId: "il-integration", row: 2, icon: "boxes",     name: "ETL / Batch Processing",
        description: "Extract, transform and load batch data between systems." },
      { id: "c-int-cdc",        layerId: "il-integration", row: 2, icon: "refresh-cw", name: "Change Data Capture (CDC)",
        description: "Real-time tracking and replication of data-source changes." },
      { id: "c-int-sft",        layerId: "il-integration", row: 2, icon: "upload",    name: "Secure File Transfer (SFT)",
        description: "Managed, audited file transfer between parties." },
      { id: "c-int-mdm",        layerId: "il-integration", row: 3, icon: "key",       name: "Master Data Management (MDM)",
        description: "Centralised, consistent enterprise master data." },
      { id: "c-int-ai",         layerId: "il-integration", row: 3, icon: "sparkles",  name: "Artificial Intelligence (AI)",
        description: "ML model integration within data and message flows." },

      // --- Producers ---
      { id: "c-prod-internal", layerId: "il-producers", row: 1, icon: "server",    name: "Internal IT Systems",
        description: "Internal systems of record producing data and services." },
      { id: "c-prod-external", layerId: "il-producers", row: 1, icon: "box",       name: "External IT Systems",
        description: "Third-party systems producing data consumed by the enterprise." },
      { id: "c-prod-partners", layerId: "il-producers", row: 1, icon: "handshake", name: "External Partners",
        description: "Partner systems producing B2B transactions." },
      { id: "c-prod-web",      layerId: "il-producers", row: 2, icon: "globe",     name: "Web Sites",
        description: "Web properties producing events and data." },
      { id: "c-prod-mobile",   layerId: "il-producers", row: 2, icon: "monitor",   name: "Mobile Apps",
        description: "Mobile applications producing telemetry and transactions." },
      { id: "c-prod-field",    layerId: "il-producers", row: 2, icon: "cpu",       name: "Field Devices",
        description: "IoT and field devices producing sensor and event data." },

      // --- Information (cross-cutting) ---
      { id: "c-info-model", layerId: "il-information", row: 1, icon: "table",     name: "Data Definition & Modelling",
        description: "Tools for creating and governing shared data models." },
      { id: "c-info-vocab", layerId: "il-information", row: 1, icon: "book-open", name: "Common Vocabulary",
        description: "Central repository of shared business objects and terms." },

      // --- Governance (cross-cutting) ---
      { id: "c-gov-catalog", layerId: "il-governance", row: 1, icon: "compass", name: "Service Catalogue & Registry",
        description: "Structured repository of APIs, microservices and their metadata." },

      // --- Security (cross-cutting) ---
      { id: "c-sec-authn",     layerId: "il-security", row: 1, icon: "fingerprint",  name: "Authentication & Authorisation",
        description: "Identity verification and role-based access control." },
      { id: "c-sec-datasec",   layerId: "il-security", row: 1, icon: "shield-check", name: "Data Security",
        description: "Encryption of data at rest and in transit." },
      { id: "c-sec-secrets",   layerId: "il-security", row: 1, icon: "key",          name: "Secrets Management",
        description: "Secure storage and rotation of credentials and keys." },
      { id: "c-sec-transport", layerId: "il-security", row: 2, icon: "lock",         name: "Transport Security",
        description: "Point-to-point TLS/SSL encryption of traffic." },
      { id: "c-sec-policy",    layerId: "il-security", row: 2, icon: "shield",       name: "Policy Enforcement",
        description: "Automated compliance and policy enforcement." },

      // --- Management & Monitoring (cross-cutting) ---
      { id: "c-mon-servicemgmt",   layerId: "il-management", row: 1, icon: "settings",  name: "Service Management",
        description: "Deployment and lifecycle operations of integration services." },
      { id: "c-mon-metrics",       layerId: "il-management", row: 1, icon: "activity",  name: "Metrics Monitoring",
        description: "Performance and availability metrics and alerting." },
      { id: "c-mon-logging",       layerId: "il-management", row: 1, icon: "file",      name: "Logging & Auditing",
        description: "Centralised log collection, analysis and audit." },
      { id: "c-mon-errorhandling", layerId: "il-management", row: 2, icon: "bell",      name: "Error Handling",
        description: "Exception capture, dead-lettering and recovery." },
      { id: "c-mon-jobsched",      layerId: "il-management", row: 2, icon: "calendar",  name: "Job Scheduling",
        description: "Unattended background and batch execution." },

      // --- Development & Testing Tools (cross-cutting) ---
      { id: "c-dev-ide",        layerId: "il-devtest", row: 1, icon: "terminal",     name: "Integrated Development Environment",
        description: "Service design and build tooling for engineers." },
      { id: "c-dev-testing",    layerId: "il-devtest", row: 1, icon: "check-circle", name: "Testing Tools",
        description: "API, contract and load testing." },
      { id: "c-dev-cicd",       layerId: "il-devtest", row: 1, icon: "git-merge",    name: "CI / CD",
        description: "Continuous integration and deployment automation." },
      { id: "c-dev-automation", layerId: "il-devtest", row: 1, icon: "code",         name: "IT Automation",
        description: "Infrastructure as Code and configuration management." },
    ],
    products: [
      { id: "ip-apigee",     icon: "plug",        name: "Apigee",              vendor: "Google",      statusId: "strategic",    notes: "Target API gateway and management plane." },
      { id: "ip-kong",       icon: "plug",        name: "Kong",                vendor: "Kong Inc.",   statusId: "emerging",     notes: "Evaluated for internal/east-west API traffic." },
      { id: "ip-mulesoft",   icon: "network",     name: "MuleSoft Anypoint",   vendor: "Salesforce",  statusId: "strategic",    notes: "Strategic ESB / iPaaS for new integrations." },
      { id: "ip-tibco",      icon: "network",     name: "TIBCO BusinessWorks", vendor: "TIBCO",       statusId: "decommission", notes: "Legacy middleware; migrate flows and exit." },
      { id: "ip-adf",        icon: "boxes",       name: "Azure Data Factory",  vendor: "Microsoft",   statusId: "strategic",    notes: "Managed ETL / batch orchestration." },
      { id: "ip-talend",     icon: "refresh-cw",  name: "Talend",              vendor: "Qlik",        statusId: "contain",      notes: "Existing batch jobs; no new build." },
      { id: "ip-debezium",   icon: "refresh-cw",  name: "Debezium",            vendor: "Open Source", statusId: "tactical",     notes: "Open-source CDC connectors." },
      { id: "ip-fivetran",   icon: "plug",        name: "Fivetran",            vendor: "Fivetran",    statusId: "strategic",    notes: "Managed CDC and connectors." },
      { id: "ip-nifi",       icon: "upload",      name: "Apache NiFi",         vendor: "Apache",      statusId: "tactical",     notes: "Managed file and dataflow transfer." },
      { id: "ip-confluent",  icon: "waves",       name: "Confluent",           vendor: "Confluent",   statusId: "strategic",    notes: "Managed event streaming backbone." },
      { id: "ip-kafka",      icon: "waves",       name: "Apache Kafka",        vendor: "Apache",      statusId: "tactical",     notes: "Self-managed clusters; consolidating onto Confluent." },
      { id: "ip-logicapps",  icon: "workflow",    name: "Azure Logic Apps",    vendor: "Microsoft",   statusId: "strategic",    notes: "Serverless workflow and orchestration." },
      { id: "ip-camunda",    icon: "workflow",    name: "Camunda",             vendor: "Camunda",     statusId: "tactical",     notes: "BPM / BRMS for stateful processes." },
      { id: "ip-sagemaker",  icon: "sparkles",    name: "Amazon SageMaker",    vendor: "AWS",         statusId: "emerging",     notes: "ML model serving within flows (pilot)." },
      { id: "ip-erwin",      icon: "table",       name: "erwin Data Modeler",  vendor: "Quest",       statusId: "contain",      notes: "Existing data models; maintained only." },
      { id: "ip-collibra",   icon: "book-open",   name: "Collibra",            vendor: "Collibra",    statusId: "strategic",    notes: "Common vocabulary and business glossary." },
      { id: "ip-backstage",  icon: "compass",     name: "Backstage",           vendor: "Open Source", statusId: "emerging",     notes: "Service catalogue and developer portal pilot." },
      { id: "ip-okta",       icon: "fingerprint", name: "Okta",                vendor: "Okta",        statusId: "strategic",    notes: "External identity and OAuth for partner APIs." },
      { id: "ip-entra",      icon: "fingerprint", name: "Microsoft Entra ID",  vendor: "Microsoft",   statusId: "strategic",    notes: "Workforce identity and token issuance." },
      { id: "ip-kms",        icon: "shield-check", name: "AWS KMS",            vendor: "AWS",         statusId: "strategic",    notes: "Encryption key management." },
      { id: "ip-vault",      icon: "key",         name: "HashiCorp Vault",     vendor: "HashiCorp",   statusId: "strategic",    notes: "Secrets, certificates and rotation." },
      { id: "ip-opa",        icon: "shield",      name: "Open Policy Agent",   vendor: "CNCF",        statusId: "emerging",     notes: "Policy-as-code enforcement pilot." },
      { id: "ip-kubernetes", icon: "boxes",       name: "Kubernetes",          vendor: "CNCF",        statusId: "strategic",    notes: "Runtime and service management platform." },
      { id: "ip-datadog",    icon: "gauge",       name: "Datadog",             vendor: "Datadog",     statusId: "strategic",    notes: "Metrics, tracing and alerting." },
      { id: "ip-grafana",    icon: "activity",    name: "Prometheus / Grafana", vendor: "Grafana Labs", statusId: "tactical",  notes: "Open-source metrics in parts of the estate." },
      { id: "ip-splunk",     icon: "file",        name: "Splunk",              vendor: "Cisco",       statusId: "contain",      notes: "Existing log analytics; cost under review." },
      { id: "ip-airflow",    icon: "calendar",    name: "Apache Airflow",      vendor: "Apache",      statusId: "strategic",    notes: "Standard job scheduler and orchestrator." },
      { id: "ip-controlm",   icon: "calendar",    name: "Control-M",           vendor: "BMC",         statusId: "contain",      notes: "Legacy enterprise scheduler; existing jobs only." },
      { id: "ip-vscode",     icon: "terminal",    name: "Visual Studio Code",  vendor: "Microsoft",   statusId: "strategic",    notes: "Standard integration development environment." },
      { id: "ip-postman",    icon: "check-circle", name: "Postman",            vendor: "Postman",     statusId: "strategic",    notes: "API design, contract and automated testing." },
      { id: "ip-github",     icon: "git-merge",   name: "GitHub Actions",      vendor: "GitHub",      statusId: "strategic",    notes: "CI/CD for integration code and config." },
      { id: "ip-jenkins",    icon: "git-merge",   name: "Jenkins",             vendor: "Open Source", statusId: "decommission", notes: "Legacy pipelines; migrating to GitHub Actions." },
      { id: "ip-terraform",  icon: "code",        name: "Terraform",           vendor: "HashiCorp",   statusId: "strategic",    notes: "IaC standard for integration infrastructure." },
      { id: "ip-ansible",    icon: "code",        name: "Ansible",             vendor: "Red Hat",     statusId: "tactical",     notes: "Configuration management." },
    ],
    mappings: {
      userUseCases: [
        { userId: "iu-integration-dev",      useCaseId: "iuc-realtime-api" },
        { userId: "iu-integration-dev",      useCaseId: "iuc-event-driven" },
        { userId: "iu-integration-dev",      useCaseId: "iuc-legacy-modernisation" },
        { userId: "iu-api-owner",            useCaseId: "iuc-realtime-api" },
        { userId: "iu-api-owner",            useCaseId: "iuc-self-service-api" },
        { userId: "iu-enterprise-architect", useCaseId: "iuc-legacy-modernisation" },
        { userId: "iu-enterprise-architect", useCaseId: "iuc-b2b-partner" },
        { userId: "iu-platform-ops",         useCaseId: "iuc-event-driven" },
        { userId: "iu-security-engineer",    useCaseId: "iuc-b2b-partner" },
        { userId: "iu-partner",              useCaseId: "iuc-b2b-partner" },
        { userId: "iu-partner",              useCaseId: "iuc-self-service-api" },
      ],
      useCaseComponents: [
        { useCaseId: "iuc-realtime-api",         componentId: "c-int-api-mgmt" },
        { useCaseId: "iuc-realtime-api",         componentId: "c-int-middleware" },
        { useCaseId: "iuc-realtime-api",         componentId: "c-sec-authn" },
        { useCaseId: "iuc-event-driven",         componentId: "c-int-esp" },
        { useCaseId: "iuc-event-driven",         componentId: "c-int-workflow" },
        { useCaseId: "iuc-event-driven",         componentId: "c-mon-metrics" },
        { useCaseId: "iuc-batch-file",           componentId: "c-int-etl" },
        { useCaseId: "iuc-batch-file",           componentId: "c-int-cdc" },
        { useCaseId: "iuc-batch-file",           componentId: "c-int-sft" },
        { useCaseId: "iuc-b2b-partner",          componentId: "c-cons-partners" },
        { useCaseId: "iuc-b2b-partner",          componentId: "c-prod-partners" },
        { useCaseId: "iuc-b2b-partner",          componentId: "c-int-api-mgmt" },
        { useCaseId: "iuc-legacy-modernisation", componentId: "c-int-middleware" },
        { useCaseId: "iuc-legacy-modernisation", componentId: "c-prod-internal" },
        { useCaseId: "iuc-legacy-modernisation", componentId: "c-int-etl" },
        { useCaseId: "iuc-self-service-api",     componentId: "c-int-api-mgmt" },
        { useCaseId: "iuc-self-service-api",     componentId: "c-gov-catalog" },
        { useCaseId: "iuc-self-service-api",     componentId: "c-sec-authn" },
      ],
      componentProducts: [
        { componentId: "c-int-api-mgmt",     productId: "ip-apigee" },
        { componentId: "c-int-api-mgmt",     productId: "ip-kong" },
        { componentId: "c-int-middleware",   productId: "ip-mulesoft" },
        { componentId: "c-int-middleware",   productId: "ip-tibco" },
        { componentId: "c-int-etl",          productId: "ip-adf" },
        { componentId: "c-int-etl",          productId: "ip-talend" },
        { componentId: "c-int-cdc",          productId: "ip-debezium" },
        { componentId: "c-int-cdc",          productId: "ip-fivetran" },
        { componentId: "c-int-sft",          productId: "ip-nifi" },
        { componentId: "c-int-esp",          productId: "ip-confluent" },
        { componentId: "c-int-esp",          productId: "ip-kafka" },
        { componentId: "c-int-workflow",     productId: "ip-logicapps" },
        { componentId: "c-int-workflow",     productId: "ip-camunda" },
        { componentId: "c-int-ai",           productId: "ip-sagemaker" },
        { componentId: "c-info-model",       productId: "ip-erwin" },
        { componentId: "c-info-vocab",       productId: "ip-collibra" },
        { componentId: "c-gov-catalog",      productId: "ip-backstage" },
        { componentId: "c-sec-authn",        productId: "ip-okta" },
        { componentId: "c-sec-authn",        productId: "ip-entra" },
        { componentId: "c-sec-datasec",      productId: "ip-kms" },
        { componentId: "c-sec-secrets",      productId: "ip-vault" },
        { componentId: "c-sec-policy",       productId: "ip-opa" },
        { componentId: "c-mon-servicemgmt",  productId: "ip-kubernetes" },
        { componentId: "c-mon-metrics",      productId: "ip-datadog" },
        { componentId: "c-mon-metrics",      productId: "ip-grafana" },
        { componentId: "c-mon-logging",      productId: "ip-splunk" },
        { componentId: "c-mon-jobsched",     productId: "ip-airflow" },
        { componentId: "c-mon-jobsched",     productId: "ip-controlm" },
        { componentId: "c-dev-ide",          productId: "ip-vscode" },
        { componentId: "c-dev-testing",      productId: "ip-postman" },
        { componentId: "c-dev-cicd",         productId: "ip-github" },
        { componentId: "c-dev-cicd",         productId: "ip-jenkins" },
        { componentId: "c-dev-automation",   productId: "ip-terraform" },
        { componentId: "c-dev-automation",   productId: "ip-ansible" },
      ],
    },
  },
});
