// ============================================================
// templates/integration.js — worked example (data only): Enterprise Integration Strategy
// Generic, illustrative reference architecture. Self-registers into window.STRATEGY_TEMPLATES.
// ============================================================

window.STRATEGY_TEMPLATES = window.STRATEGY_TEMPLATES || [];
window.STRATEGY_TEMPLATES.push({
  id: "integration",
  name: "Integration Strategy (example)",
  description: "Enterprise integration: API management, iPaaS/ESB, event streaming, B2B and connectivity across 10 layers.",
  source: "Inspired by IT Architecture Patterns",
  sourceUrl: "https://www.itarchitecturepatterns.net/reference-architectures",
  data: {
    schemaVersion: 1,
    meta: {
      title: "Example: Enterprise Integration Strategy",
      organisation: "Example Organisation",
      author: "",
    },
    statuses: [
      { id: "strategic",    name: "Strategic",    color: "#16a34a", description: "Invest and grow — the target state.", order: 1 },
      { id: "emerging",     name: "Emerging",     color: "#7c3aed", description: "Under evaluation / pilot.", order: 2 },
      { id: "tactical",     name: "Tactical",     color: "#f59e0b", description: "Acceptable for now; not the target.", order: 3 },
      { id: "contain",      name: "Contain",      color: "#64748b", description: "No new investment or workloads.", order: 4 },
      { id: "decommission", name: "Decommission", color: "#dc2626", description: "Actively exiting.", order: 5 },
    ],
    users: [
      { id: "iu-integration-dev", icon: "code", name: "Integration Developer", type: "primary",
        description: "Builds and maintains APIs, flows, event pipelines and connectors across systems.",
        goals: ["Reusable integration patterns", "Fast, safe deployment", "Good local testing and mocking"],
        painPoints: ["Point-to-point spaghetti", "Undocumented legacy interfaces", "Slow manual releases"] },
      { id: "iu-api-owner", icon: "package", name: "API Product Owner", type: "primary",
        description: "Owns API products end to end: their contracts, versions, consumers and adoption.",
        goals: ["Well-documented, versioned APIs", "Self-service onboarding", "Clear usage analytics"],
        painPoints: ["Breaking changes surprising consumers", "No visibility of who uses what"] },
      { id: "iu-enterprise-architect", icon: "compass", name: "Enterprise Architect", type: "secondary",
        description: "Sets integration standards and steers the move off legacy middleware.",
        goals: ["Consistent standards across teams", "A clear target-state platform", "Reduced vendor sprawl"],
        painPoints: ["Multiple overlapping ESB/iPaaS tools", "No single source of interface truth"] },
      { id: "iu-platform-ops", icon: "settings", name: "Platform Operations", type: "secondary",
        description: "Runs, scales and monitors the integration runtime; first responder to incidents.",
        goals: ["Reliable, observable runtimes", "Automated scaling and recovery"],
        painPoints: ["Silent message failures", "Hard-to-trace cross-system flows"] },
      { id: "iu-security-engineer", icon: "shield", name: "Security Engineer", type: "secondary",
        description: "Secures APIs and integration flows: authentication, authorisation, secrets and threat protection.",
        goals: ["Consistent OAuth/OIDC everywhere", "Central secret and certificate management"],
        painPoints: ["Inconsistent auth per team", "Credentials in config files"] },
      { id: "iu-partner", icon: "handshake", name: "External Partner / Consumer", type: "external",
        description: "Partners and third parties that consume APIs or exchange B2B messages.",
        goals: ["Stable, documented APIs", "Secure self-service access", "Reliable B2B exchange"],
        painPoints: ["Ad-hoc file drops", "No SLAs or change notice"] },
    ],
    useCases: [
      { id: "iuc-realtime-api", icon: "plug", name: "Real-Time API Integration",
        description: "Expose and consume synchronous REST/GraphQL APIs between applications and partners.",
        businessValue: "Real-time experiences and decoupled applications." },
      { id: "iuc-event-driven", icon: "waves", name: "Event-Driven Integration",
        description: "Publish and subscribe to business events for loosely-coupled, reactive processing.",
        businessValue: "React in seconds and scale services independently." },
      { id: "iuc-batch-file", icon: "upload", name: "Batch & File Integration",
        description: "Scheduled and managed file transfers with transformation between systems.",
        businessValue: "Reliable movement of bulk and legacy data." },
      { id: "iuc-b2b-partner", icon: "handshake", name: "B2B / Partner Integration",
        description: "Exchange EDI and API-based transactions securely with external partners.",
        businessValue: "Automated, auditable partner trading." },
      { id: "iuc-legacy-modernisation", icon: "refresh-cw", name: "Legacy Modernisation",
        description: "Wrap and gradually replace legacy middleware and mainframe interfaces with modern APIs and events.",
        businessValue: "Lower risk and cost; retire ageing platforms." },
      { id: "iuc-self-service-api", icon: "book-open", name: "Self-Service API Consumption",
        description: "Developers discover, subscribe to and consume governed API products via a portal.",
        businessValue: "Faster delivery; less integration backlog." },
    ],
    layers: [
      { id: "il-consumers",    name: "Integration Consumers",     color: "slate",  order: 1, orientation: "vertical",
        description: "The applications, partners and systems that consume integrations." },
      { id: "il-api",          name: "API Management",            color: "blue",   order: 2, orientation: "vertical",
        description: "Exposes, secures, meters and catalogs API products." },
      { id: "il-integration",  name: "Integration & Orchestration", color: "purple", order: 3, orientation: "vertical",
        description: "Mediates, transforms and orchestrates flows between systems." },
      { id: "il-messaging",    name: "Messaging & Eventing",      color: "cyan",   order: 4, orientation: "vertical",
        description: "Asynchronous messaging and event streaming backbone." },
      { id: "il-connectivity", name: "Connectivity & Adapters",   color: "amber",  order: 5, orientation: "vertical",
        description: "Protocol adapters, connectors and B2B/file gateways to systems." },
      { id: "il-systems",      name: "Systems of Record",         color: "teal",   order: 6, orientation: "vertical",
        description: "The applications and data stores being integrated." },
      { id: "il-runtime",      name: "Runtime & Infrastructure",  color: "indigo", order: 7, orientation: "vertical",
        description: "The compute, network and hybrid foundations hosting integration workloads." },
      { id: "il-security",     name: "API & Integration Security", color: "rose",  order: 8, orientation: "cross-cutting",
        description: "Authentication, authorisation, secrets and threat protection across every layer." },
      { id: "il-governance",   name: "Governance & Observability", color: "green", order: 9, orientation: "cross-cutting",
        description: "Lifecycle governance, monitoring, logging and contracts across every layer." },
      { id: "il-devops",       name: "Integration DevOps",        color: "lime",   order: 10, orientation: "cross-cutting",
        description: "Design, CI/CD, IaC and testing that deliver integrations safely." },
    ],
    components: [
      { id: "i-web-mobile",          layerId: "il-consumers", row: 1, icon: "monitor",   name: "Web & Mobile Apps",
        description: "Customer and staff applications consuming APIs in real time." },
      { id: "i-internal-apps",       layerId: "il-consumers", row: 1, icon: "box",       name: "Internal Applications",
        description: "Line-of-business systems calling and receiving integrations." },
      { id: "i-partner-systems",     layerId: "il-consumers", row: 1, icon: "handshake", name: "Partner Systems (B2B)",
        description: "External partner systems exchanging transactions." },
      { id: "i-automated-consumers", layerId: "il-consumers", row: 2, icon: "bot",       name: "Automated Consumers",
        description: "Bots, RPA and downstream automations consuming events and APIs." },
      { id: "i-devportal-users",     layerId: "il-consumers", row: 2, icon: "users",     name: "Developer Community",
        description: "Internal and partner developers discovering and using API products." },

      { id: "i-api-gateway",   layerId: "il-api", row: 1, icon: "plug",      name: "API Gateway",
        description: "Secures, routes and mediates inbound and outbound API traffic." },
      { id: "i-dev-portal",    layerId: "il-api", row: 1, icon: "book-open", name: "Developer Portal",
        description: "Self-service discovery, docs, keys and onboarding for API products." },
      { id: "i-api-catalog",   layerId: "il-api", row: 1, icon: "table",     name: "API Catalog & Registry",
        description: "Authoritative inventory of API products, versions and specs." },
      { id: "i-rate-limiting", layerId: "il-api", row: 2, icon: "gauge",     name: "Rate Limiting & Quotas",
        description: "Traffic policies protecting backends and enforcing plans." },
      { id: "i-api-analytics", layerId: "il-api", row: 2, icon: "bar-chart", name: "API Analytics",
        description: "Usage, adoption, latency and error metrics per API product." },

      { id: "i-ipaas",          layerId: "il-integration", row: 1, icon: "boxes",     name: "Integration Platform (iPaaS)",
        description: "Cloud integration platform for flows, connectors and orchestration." },
      { id: "i-esb",            layerId: "il-integration", row: 1, icon: "network",   name: "Enterprise Service Bus",
        description: "Legacy mediation and routing backbone being modernised." },
      { id: "i-orchestration",  layerId: "il-integration", row: 1, icon: "workflow",  name: "Orchestration & Workflow",
        description: "Coordinates multi-step, stateful integration processes." },
      { id: "i-transformation", layerId: "il-integration", row: 2, icon: "refresh-cw", name: "Transformation & Mapping",
        description: "Data mapping, enrichment and format conversion between systems." },
      { id: "i-business-rules", layerId: "il-integration", row: 2, icon: "filter",    name: "Business Rules Engine",
        description: "Externalised decision logic applied within integration flows." },

      { id: "i-message-broker",  layerId: "il-messaging", row: 1, icon: "radio",   name: "Message Broker",
        description: "Reliable queuing for asynchronous point-to-point messaging." },
      { id: "i-event-streaming", layerId: "il-messaging", row: 1, icon: "waves",   name: "Event Streaming",
        description: "Durable, replayable log for high-volume event streams." },
      { id: "i-event-router",    layerId: "il-messaging", row: 1, icon: "share-2", name: "Event Router",
        description: "Filters and routes events to interested subscribers." },
      { id: "i-pubsub-topics",   layerId: "il-messaging", row: 2, icon: "layers",  name: "Pub/Sub Topics",
        description: "Topic and subscription model decoupling producers and consumers." },
      { id: "i-dead-letter",     layerId: "il-messaging", row: 2, icon: "file",    name: "Dead Letter Handling",
        description: "Captures, inspects and replays failed messages." },

      { id: "i-protocol-adapters", layerId: "il-connectivity", row: 1, icon: "plug",   name: "Protocol Adapters",
        description: "Bridges HTTP, SOAP, JMS, gRPC, FTP and other protocols." },
      { id: "i-connectors",        layerId: "il-connectivity", row: 1, icon: "link",   name: "Prebuilt Connectors",
        description: "Managed connectors to SaaS and packaged applications." },
      { id: "i-mft",               layerId: "il-connectivity", row: 1, icon: "upload", name: "Managed File Transfer",
        description: "Secure, auditable transfer of files and bulk data." },
      { id: "i-edi-gateway",       layerId: "il-connectivity", row: 2, icon: "file",   name: "EDI / B2B Gateway",
        description: "Trading-partner EDI, AS2 and document exchange." },
      { id: "i-legacy-adapters",   layerId: "il-connectivity", row: 2, icon: "server", name: "Legacy Adapters",
        description: "Adapters to mainframe and legacy transaction systems." },

      { id: "i-core-apps",     layerId: "il-systems", row: 1, icon: "box",      name: "Core Business Applications",
        description: "ERP, CRM and other core systems of record." },
      { id: "i-saas-apps",     layerId: "il-systems", row: 1, icon: "package",  name: "SaaS Applications",
        description: "Cloud SaaS products integrated via APIs and connectors." },
      { id: "i-databases",     layerId: "il-systems", row: 1, icon: "database", name: "Databases",
        description: "Operational databases exposed through integration." },
      { id: "i-mainframe",     layerId: "il-systems", row: 2, icon: "server",   name: "Mainframe / Legacy",
        description: "Legacy transaction platforms being wrapped and retired." },
      { id: "i-partner-apis",  layerId: "il-systems", row: 2, icon: "globe",    name: "External Partner APIs",
        description: "Third-party APIs consumed by the enterprise." },

      { id: "i-container-platform", layerId: "il-runtime", row: 1, icon: "boxes",   name: "Container Platform",
        description: "Orchestrates containerised integration runtimes." },
      { id: "i-cloud-runtime",      layerId: "il-runtime", row: 1, icon: "cloud",   name: "Cloud Runtime",
        description: "Managed cloud compute hosting gateways and flows." },
      { id: "i-private-networking", layerId: "il-runtime", row: 1, icon: "network", name: "Private Networking",
        description: "Private endpoints and connectivity to on-prem systems." },
      { id: "i-hybrid-gateway",     layerId: "il-runtime", row: 1, icon: "server",  name: "On-Prem / Hybrid Gateway",
        description: "Runtime bridging cloud integration to on-premise systems." },

      { id: "i-api-auth",      layerId: "il-security", row: 1, icon: "fingerprint",  name: "API Authentication",
        description: "OAuth 2.0 / OIDC authentication for APIs and consumers." },
      { id: "i-authz-policy",  layerId: "il-security", row: 1, icon: "lock",         name: "Authorization & Policy",
        description: "Fine-grained, policy-based access control for APIs and flows." },
      { id: "i-secrets-certs", layerId: "il-security", row: 1, icon: "key",          name: "Secrets & Certificates",
        description: "Central storage and rotation of credentials, keys and certs." },
      { id: "i-threat-waf",    layerId: "il-security", row: 2, icon: "shield",       name: "Threat Protection / WAF",
        description: "Bot, DDoS and payload threat protection at the edge." },
      { id: "i-tokenization",  layerId: "il-security", row: 2, icon: "shield-check", name: "Tokenization & Encryption",
        description: "Protects sensitive payloads in transit and at rest." },

      { id: "i-api-lifecycle",  layerId: "il-governance", row: 1, icon: "compass",      name: "API Lifecycle Governance",
        description: "Standards, versioning and approval across the API estate." },
      { id: "i-monitoring",     layerId: "il-governance", row: 1, icon: "activity",     name: "Monitoring & Tracing",
        description: "End-to-end tracing, metrics and alerting across flows." },
      { id: "i-logging-audit",  layerId: "il-governance", row: 1, icon: "file",         name: "Logging & Audit",
        description: "Tamper-evident logs of transactions and administration." },
      { id: "i-sla-contracts",  layerId: "il-governance", row: 2, icon: "check-circle", name: "SLA & Contract Management",
        description: "Consumer contracts, SLAs and deprecation management." },
      { id: "i-service-catalog", layerId: "il-governance", row: 2, icon: "book-open",   name: "Service Catalog",
        description: "Discoverable catalog of integration and API services." },

      { id: "i-cicd",            layerId: "il-devops", row: 1, icon: "git-merge",    name: "CI/CD Pipelines",
        description: "Automated build, test and deployment of integrations." },
      { id: "i-iac",             layerId: "il-devops", row: 1, icon: "code",         name: "Infrastructure as Code",
        description: "Declarative provisioning of gateways, runtimes and config." },
      { id: "i-api-design",      layerId: "il-devops", row: 1, icon: "terminal",     name: "API Design & Spec",
        description: "OpenAPI/AsyncAPI design-first tooling and mocking." },
      { id: "i-test-automation", layerId: "il-devops", row: 1, icon: "check-circle", name: "Test Automation",
        description: "Contract, integration and regression test automation." },
    ],
    products: [
      { id: "ip-apigee",     icon: "plug",        name: "Apigee",                vendor: "Google",     statusId: "strategic",    notes: "Target API gateway and management plane." },
      { id: "ip-kong",       icon: "plug",        name: "Kong",                  vendor: "Kong Inc.",  statusId: "emerging",     notes: "Evaluated for internal/east-west API traffic." },
      { id: "ip-mulesoft",   icon: "boxes",       name: "MuleSoft Anypoint",     vendor: "Salesforce", statusId: "strategic",    notes: "Strategic iPaaS for new integrations and connectors." },
      { id: "ip-boomi",      icon: "boxes",       name: "Boomi",                 vendor: "Boomi",      statusId: "contain",      notes: "Existing flows remain; no new build." },
      { id: "ip-logicapps",  icon: "workflow",    name: "Azure Logic Apps",      vendor: "Microsoft",  statusId: "strategic",    notes: "Serverless orchestration for cloud-native flows." },
      { id: "ip-camel",      icon: "refresh-cw",  name: "Apache Camel",          vendor: "Apache",     statusId: "tactical",     notes: "Code-first routes where teams prefer Java." },
      { id: "ip-webmethods", icon: "network",     name: "webMethods ESB",        vendor: "Software AG", statusId: "decommission", notes: "Legacy ESB; migrate flows to iPaaS by target date." },
      { id: "ip-tibco",      icon: "network",     name: "TIBCO BusinessWorks",   vendor: "TIBCO",      statusId: "decommission", notes: "Legacy integration; actively exiting." },
      { id: "ip-confluent",  icon: "waves",       name: "Confluent",             vendor: "Confluent",  statusId: "strategic",    notes: "Managed event streaming backbone." },
      { id: "ip-kafka",      icon: "waves",       name: "Apache Kafka",          vendor: "Apache",     statusId: "tactical",     notes: "Self-managed clusters; consolidating onto Confluent." },
      { id: "ip-rabbitmq",   icon: "radio",       name: "RabbitMQ",              vendor: "Broadcom",   statusId: "tactical",     notes: "Existing queuing workloads." },
      { id: "ip-servicebus", icon: "radio",       name: "Azure Service Bus",     vendor: "Microsoft",  statusId: "strategic",    notes: "Managed broker for cloud messaging." },
      { id: "ip-solace",     icon: "share-2",     name: "Solace PubSub+",        vendor: "Solace",     statusId: "emerging",     notes: "Event mesh pilot for routing across environments." },
      { id: "ip-moveit",     icon: "upload",      name: "MOVEit",                vendor: "Progress",   statusId: "tactical",     notes: "Managed file transfer for bulk exchange." },
      { id: "ip-sterling",   icon: "file",        name: "IBM Sterling B2B",      vendor: "IBM",        statusId: "contain",      notes: "EDI trading; maintained, not extended." },
      { id: "ip-backstage",  icon: "book-open",   name: "Backstage",             vendor: "Open Source", statusId: "emerging",    notes: "Developer portal pilot for API discovery." },
      { id: "ip-postman",    icon: "terminal",    name: "Postman",               vendor: "Postman",    statusId: "strategic",    notes: "API design, mocking and automated testing." },
      { id: "ip-swaggerhub", icon: "terminal",    name: "SwaggerHub",            vendor: "SmartBear",  statusId: "tactical",     notes: "OpenAPI design for existing teams." },
      { id: "ip-okta",       icon: "fingerprint", name: "Okta",                  vendor: "Okta",       statusId: "strategic",    notes: "External identity and OAuth for partner APIs." },
      { id: "ip-entra",      icon: "fingerprint", name: "Microsoft Entra ID",    vendor: "Microsoft",  statusId: "strategic",    notes: "Workforce identity and token issuance." },
      { id: "ip-vault",      icon: "key",         name: "HashiCorp Vault",       vendor: "HashiCorp",  statusId: "strategic",    notes: "Secrets, certificates and rotation." },
      { id: "ip-datadog",    icon: "gauge",       name: "Datadog",               vendor: "Datadog",    statusId: "strategic",    notes: "Distributed tracing and API observability." },
      { id: "ip-dynatrace",  icon: "gauge",       name: "Dynatrace",             vendor: "Dynatrace",  statusId: "tactical",     notes: "APM in parts of the estate." },
      { id: "ip-kubernetes", icon: "boxes",       name: "Kubernetes",            vendor: "CNCF",       statusId: "strategic",    notes: "Container platform for integration runtimes." },
      { id: "ip-terraform",  icon: "code",        name: "Terraform",             vendor: "HashiCorp",  statusId: "strategic",    notes: "IaC standard for integration infrastructure." },
      { id: "ip-github",     icon: "git-merge",   name: "GitHub Actions",        vendor: "GitHub",     statusId: "strategic",    notes: "CI/CD for integration code and config." },
    ],
    mappings: {
      userUseCases: [
        { userId: "iu-integration-dev",      useCaseId: "iuc-realtime-api" },
        { userId: "iu-integration-dev",      useCaseId: "iuc-event-driven" },
        { userId: "iu-integration-dev",      useCaseId: "iuc-legacy-modernisation" },
        { userId: "iu-api-owner",            useCaseId: "iuc-realtime-api" },
        { userId: "iu-api-owner",            useCaseId: "iuc-self-service-api" },
        { userId: "iu-enterprise-architect", useCaseId: "iuc-legacy-modernisation" },
        { userId: "iu-enterprise-architect", useCaseId: "iuc-b2b-partner" },
        { userId: "iu-platform-ops",         useCaseId: "iuc-event-driven" },
        { userId: "iu-security-engineer",    useCaseId: "iuc-b2b-partner" },
        { userId: "iu-partner",              useCaseId: "iuc-b2b-partner" },
        { userId: "iu-partner",              useCaseId: "iuc-self-service-api" },
      ],
      useCaseComponents: [
        { useCaseId: "iuc-realtime-api",          componentId: "i-api-gateway" },
        { useCaseId: "iuc-realtime-api",          componentId: "i-ipaas" },
        { useCaseId: "iuc-realtime-api",          componentId: "i-protocol-adapters" },
        { useCaseId: "iuc-realtime-api",          componentId: "i-api-auth" },
        { useCaseId: "iuc-event-driven",          componentId: "i-event-streaming" },
        { useCaseId: "iuc-event-driven",          componentId: "i-message-broker" },
        { useCaseId: "iuc-event-driven",          componentId: "i-event-router" },
        { useCaseId: "iuc-event-driven",          componentId: "i-orchestration" },
        { useCaseId: "iuc-batch-file",            componentId: "i-mft" },
        { useCaseId: "iuc-batch-file",            componentId: "i-transformation" },
        { useCaseId: "iuc-batch-file",            componentId: "i-connectors" },
        { useCaseId: "iuc-b2b-partner",           componentId: "i-edi-gateway" },
        { useCaseId: "iuc-b2b-partner",           componentId: "i-partner-apis" },
        { useCaseId: "iuc-b2b-partner",           componentId: "i-api-gateway" },
        { useCaseId: "iuc-legacy-modernisation",  componentId: "i-esb" },
        { useCaseId: "iuc-legacy-modernisation",  componentId: "i-legacy-adapters" },
        { useCaseId: "iuc-legacy-modernisation",  componentId: "i-mainframe" },
        { useCaseId: "iuc-legacy-modernisation",  componentId: "i-ipaas" },
        { useCaseId: "iuc-self-service-api",      componentId: "i-dev-portal" },
        { useCaseId: "iuc-self-service-api",      componentId: "i-api-catalog" },
        { useCaseId: "iuc-self-service-api",      componentId: "i-api-gateway" },
        { useCaseId: "iuc-self-service-api",      componentId: "i-api-analytics" },
      ],
      componentProducts: [
        { componentId: "i-api-gateway",       productId: "ip-apigee" },
        { componentId: "i-api-gateway",       productId: "ip-kong" },
        { componentId: "i-dev-portal",        productId: "ip-backstage" },
        { componentId: "i-api-analytics",     productId: "ip-datadog" },
        { componentId: "i-ipaas",             productId: "ip-mulesoft" },
        { componentId: "i-ipaas",             productId: "ip-boomi" },
        { componentId: "i-esb",               productId: "ip-webmethods" },
        { componentId: "i-esb",               productId: "ip-tibco" },
        { componentId: "i-orchestration",     productId: "ip-logicapps" },
        { componentId: "i-orchestration",     productId: "ip-camel" },
        { componentId: "i-transformation",    productId: "ip-camel" },
        { componentId: "i-message-broker",    productId: "ip-rabbitmq" },
        { componentId: "i-message-broker",    productId: "ip-servicebus" },
        { componentId: "i-event-streaming",   productId: "ip-confluent" },
        { componentId: "i-event-streaming",   productId: "ip-kafka" },
        { componentId: "i-event-router",      productId: "ip-solace" },
        { componentId: "i-connectors",        productId: "ip-mulesoft" },
        { componentId: "i-mft",               productId: "ip-moveit" },
        { componentId: "i-edi-gateway",       productId: "ip-sterling" },
        { componentId: "i-container-platform", productId: "ip-kubernetes" },
        { componentId: "i-api-auth",          productId: "ip-okta" },
        { componentId: "i-api-auth",          productId: "ip-entra" },
        { componentId: "i-secrets-certs",     productId: "ip-vault" },
        { componentId: "i-monitoring",        productId: "ip-datadog" },
        { componentId: "i-monitoring",        productId: "ip-dynatrace" },
        { componentId: "i-cicd",              productId: "ip-github" },
        { componentId: "i-iac",               productId: "ip-terraform" },
        { componentId: "i-api-design",        productId: "ip-postman" },
        { componentId: "i-api-design",        productId: "ip-swaggerhub" },
        { componentId: "i-test-automation",   productId: "ip-postman" },
      ],
    },
  },
});
