// ============================================================
// templates/security.js — worked example (data only): Security Strategy
// Layers and components are generated from the Security Reference Architecture at itarchitecturepatterns.net
// by scripts/sync-strategy-templates.ts; users, use cases and products are hand-written.
// Products are an illustrative example organisation's choices (like the other templates), drawn from the
// examples in the Security Reference Architecture — not recommendations.
// Self-registers into window.STRATEGY_TEMPLATES so it works from file://.
// ============================================================

window.STRATEGY_TEMPLATES = window.STRATEGY_TEMPLATES || [];
window.STRATEGY_TEMPLATES.push({
  id: "security",
  name: "Security Strategy (example)",
  description: "Security strategy built on the Security Reference Architecture: a Zero Trust control plane, seven asset-class layers from identity to AI agents, and five cross-cutting layers.",
  source: "Security Reference Architecture",
  sourceUrl: "https://itarchitecturepatterns.net/reference-architectures/security-reference-architecture",
  sourceArchitecture: "security-reference-architecture",
  lastSynced: "2026-09-17",
  data: {
    schemaVersion: 1,
    meta: { title: "Example: Security Strategy", organisation: "Example Organisation", author: "" },
    statuses: [
      { id: "strategic", name: "Strategic", color: "#16a34a", description: "Invest and grow — the target state.", order: 1 },
      { id: "emerging", name: "Emerging", color: "#7c3aed", description: "Under evaluation / pilot.", order: 2 },
      { id: "tactical", name: "Tactical", color: "#f59e0b", description: "Acceptable for now; not the target.", order: 3 },
      { id: "contain", name: "Contain", color: "#64748b", description: "No new investment or workloads.", order: 4 },
      { id: "decommission", name: "Decommission", color: "#dc2626", description: "Actively exiting.", order: 5 }
    ],
    users: [
      { id: "su-ciso", icon: "shield", name: "CISO", type: "primary",
        description: "Owns the security strategy, the risk posture reported to the board, and the security budget.",
        goals: ["A defensible, measurable risk posture","Evidence the security investment is reducing risk","Confidence the organisation can recover from a major incident"],
        painPoints: ["Tool sprawl with overlapping spend","No single view of control coverage","Audit findings discovered too late"] },
      { id: "su-security-architect", icon: "compass", name: "Security Architect", type: "primary",
        description: "Designs security into platforms and solutions and sets the patterns delivery teams build to.",
        goals: ["Reusable patterns teams adopt by default","Access decisions made consistently in one place","Security that does not slow delivery"],
        painPoints: ["Every project reinvents authentication","Controls bolted on after design","Legacy systems that cannot meet the standard"] },
      { id: "su-soc-analyst", icon: "bell", name: "SOC Analyst", type: "primary",
        description: "Monitors, triages and investigates alerts, and leads the first response to security incidents.",
        goals: ["High-fidelity alerts with context","Fast, automated containment","Complete, trustworthy logs"],
        painPoints: ["Alert fatigue from noisy detections","Blind spots in cloud and SaaS","Manual, repetitive containment steps"] },
      { id: "su-platform-engineer", icon: "cloud", name: "Cloud & Platform Engineer", type: "primary",
        description: "Builds and runs the cloud landing zones, networks and shared platforms that workloads run on.",
        goals: ["Guardrails that are secure by default","Least-privilege access that is easy to request","Misconfiguration caught before deployment"],
        painPoints: ["Standing administrator access","Configuration drift across accounts","Firewall change tickets that take weeks"] },
      { id: "su-developer", icon: "code", name: "Application Developer", type: "secondary",
        description: "Builds and changes applications and APIs, and increasingly features that use AI models.",
        goals: ["Security feedback inside the pipeline","Secrets that never live in code","Clear guidance on using AI safely"],
        painPoints: ["Late findings that block a release","False positives from scanners","Unclear rules for AI and data use"] },
      { id: "su-risk-compliance", icon: "check-circle", name: "Risk & Compliance Manager", type: "secondary",
        description: "Maps controls to regulatory and framework obligations and prepares evidence for auditors.",
        goals: ["Continuous, automated evidence","One control satisfying many obligations","Early warning of control failures"],
        painPoints: ["Spreadsheet-driven audits","Evidence gathered in a rush before each audit","No link between risks and the controls that treat them"] },
      { id: "su-workforce", icon: "users", name: "Workforce User", type: "secondary",
        description: "Every employee and contractor who signs in to systems to do their job, on managed and personal devices.",
        goals: ["One sign-in that just works","Access from anywhere without a VPN","Not being blamed for clicking the wrong link"],
        painPoints: ["Repeated MFA prompts","Slow VPN connections","Waiting days for access to be granted"] },
      { id: "su-supplier", icon: "handshake", name: "Third-Party Supplier", type: "external",
        description: "Partners, contractors and vendors who need scoped access to systems or who supply software the organisation runs.",
        goals: ["Simple, time-bound access to exactly what they support","Clear security expectations up front"],
        painPoints: ["Shared accounts and long-lived credentials","Repeated, inconsistent security questionnaires"] }
    ],
    useCases: [
      { id: "suc-zero-trust-access", icon: "lock", name: "Zero Trust Access",
        description: "Every request to an application is authenticated, checked against device posture and policy, and enforced close to the resource — with no implicit trust from network location.",
        businessValue: "Secure access from anywhere, and a much smaller blast radius when a credential is compromised." },
      { id: "suc-privileged-access", icon: "key", name: "Privileged Access Control",
        description: "Administrative access is requested, approved, time-bound and recorded, with a governed break-glass path.",
        businessValue: "Removes standing admin rights, the most common route to a major breach." },
      { id: "suc-secure-delivery", icon: "git-branch", name: "Secure Software Delivery",
        description: "Code, dependencies, containers and infrastructure definitions are checked in the pipeline, and artefacts are signed and inventoried.",
        businessValue: "Vulnerabilities found when they are cheapest to fix, and fast answers when a new dependency flaw is announced." },
      { id: "suc-protect-sensitive-data", icon: "shield-check", name: "Protect Sensitive Data",
        description: "Sensitive data is discovered and classified, encrypted, masked where it is shown, and prevented from leaving without authorisation.",
        businessValue: "Reduced likelihood and impact of a data breach, and demonstrable privacy compliance." },
      { id: "suc-detect-respond", icon: "bell", name: "Detect & Respond to Threats",
        description: "Telemetry from identity, endpoints, cloud and applications is correlated into detections, investigated, and contained quickly — automatically where possible.",
        businessValue: "Shorter attacker dwell time and less damage per incident." },
      { id: "suc-ransomware-recovery", icon: "refresh-cw", name: "Recover from Ransomware",
        description: "Critical services can be restored from backups an attacker cannot encrypt or delete, following a rehearsed plan with clear communication.",
        businessValue: "The organisation survives a destructive attack without paying a ransom." },
      { id: "suc-adopt-ai-safely", icon: "sparkles", name: "Adopt AI Safely",
        description: "AI models and agents are approved for defined uses, filtered for injection and data leakage, limited in what they can do, and fully logged.",
        businessValue: "The business can use AI without creating an unmanaged new route for data loss." },
      { id: "suc-demonstrate-compliance", icon: "check-circle", name: "Demonstrate Compliance",
        description: "Controls are mapped to the frameworks the organisation is measured against, tested continuously, and backed by evidence collected automatically.",
        businessValue: "Faster, cheaper audits and fewer surprises from regulators." },
      { id: "suc-third-party-risk", icon: "handshake", name: "Manage Third-Party Risk",
        description: "Suppliers are assessed in proportion to their access, given scoped, time-bound access, and the software they supply is inventoried and verified.",
        businessValue: "Reduced exposure to supply-chain attacks and supplier-caused breaches." }
    ],
    layers: [
      { id: "l-control-plane", sourceId: "control-plane", name: "Control Plane", color: "indigo", order: 1, orientation: "vertical", description: "Zero Trust is not a product tier — it is the decision that every request is evaluated on its merits rather than trusted because of where it came from. Three logical components make that possible, and separating them is what distinguishes an architecture from an application with roles in it." },
      { id: "l-identity-and-access", sourceId: "identity-and-access", name: "Identity & Access", color: "blue", order: 2, orientation: "vertical", description: "Establishes who or what is making a request, and what they are permitted to do. The foundation every other layer depends on — a compromised identity bypasses most other controls." },
      { id: "l-endpoint-and-device-trust", sourceId: "endpoint-and-device-trust", name: "Endpoint & Device Trust", color: "teal", order: 3, orientation: "vertical", description: "Establishes whether the device carrying a request is in a state fit to be trusted. Posture is half of what makes conditional access meaningful; without it, Zero Trust reduces to identity alone." },
      { id: "l-network-and-infrastructure", sourceId: "network-and-infrastructure", name: "Network & Infrastructure", color: "green", order: 4, orientation: "vertical", description: "Controls reachability. Modern practice moves from a hardened perimeter towards identity-aware access and segmentation that limits how far an intruder can travel." },
      { id: "l-application-and-api", sourceId: "application-and-api", name: "Application & API", color: "purple", order: 5, orientation: "vertical", description: "Secures what the organisation builds and exposes. Split between assurance activities *before* deployment and protection *at runtime*." },
      { id: "l-data-protection", sourceId: "data-protection", name: "Data Protection", color: "amber", order: 6, orientation: "vertical", description: "Protects the data itself, so that a control failure elsewhere does not automatically become a disclosure." },
      { id: "l-cloud-platform", sourceId: "cloud-platform", name: "Cloud Platform", color: "cyan", order: 7, orientation: "vertical", description: "Secures the control plane of the cloud itself. Most cloud incidents originate in configuration rather than in exploitation of a vulnerability." },
      { id: "l-ai-and-autonomous-agents", sourceId: "ai-and-autonomous-agents", name: "AI & Autonomous Agents", color: "purple", order: 8, orientation: "vertical", description: "Secures AI systems and the agents acting on their output. The newest layer and the least settled — the threat model differs from conventional application security because the *input itself* can carry instructions." },
      { id: "l-governance-risk-and-compliance", sourceId: "governance-risk-and-compliance", name: "Governance, Risk & Compliance", color: "amber", order: 9, orientation: "cross-cutting", description: "Establishes what the organisation is trying to achieve, what it is prepared to tolerate, and how it demonstrates both." },
      { id: "l-people-and-insider-risk", sourceId: "people-and-insider-risk", name: "People & Insider Risk", color: "amber", order: 10, orientation: "cross-cutting", description: "Addresses the fact that most incidents involve a person — through error, coercion or intent — rather than a purely technical failure." },
      { id: "l-supply-chain-and-third-party-risk", sourceId: "supply-chain-and-third-party-risk", name: "Supply Chain & Third-Party Risk", color: "lime", order: 11, orientation: "cross-cutting", description: "Extends assurance to software and organisations outside the boundary, which increasingly carry the same access as employees." },
      { id: "l-detection-and-security-operations", sourceId: "detection-and-security-operations", name: "Detection & Security Operations", color: "rose", order: 12, orientation: "cross-cutting", description: "Assumes prevention will sometimes fail, and shortens the time between that happening and someone knowing." },
      { id: "l-response-continuity-and-recovery", sourceId: "response-continuity-and-recovery", name: "Response, Continuity & Recovery", color: "rose", order: 13, orientation: "cross-cutting", description: "Limits damage once something has happened, and restores service afterwards." }
    ],
    components: [
      { id: "c-policy-engine-pe", sourceId: "policy-engine-pe", layerId: "l-control-plane", icon: "sparkles", name: "Policy Engine (PE)", description: "Makes the decision. Evaluates each request against policy, identity, device posture, behavioural history and threat intelligence to produce an allow, deny or step-up outcome. Owns the trust algorithm." },
      { id: "c-policy-administrator-pa", sourceId: "policy-administrator-pa", layerId: "l-control-plane", icon: "settings", name: "Policy Administrator (PA)", description: "Executes the decision. Establishes or terminates the session, issues and revokes the credentials the enforcement point will accept. The bridge between deciding and enforcing." },
      { id: "c-policy-enforcement-point-pep", sourceId: "policy-enforcement-point-pep", layerId: "l-control-plane", icon: "shield-check", name: "Policy Enforcement Point (PEP)", description: "Sits in the data plane immediately in front of the resource and actually permits or blocks the connection. There are usually many PEPs for one PE." },
      { id: "c-trust-signal-sources", sourceId: "trust-signal-sources", layerId: "l-control-plane", icon: "target", name: "Trust Signal Sources", description: "Feed the engine the context it needs: device posture, identity risk score, threat feeds, session anomaly, data classification. Decision quality is bounded by signal quality." },
      { id: "c-directory-services", sourceId: "directory-services", layerId: "l-identity-and-access", icon: "book-open", name: "Directory Services", description: "The authoritative store of user, group and device records. Frequently a legacy on-premises directory that must be integrated with, rather than replaced, for years." },
      { id: "c-federation-and-single-sign-on", sourceId: "federation-and-single-sign-on", layerId: "l-identity-and-access", icon: "link", name: "Federation & Single Sign-On", description: "Exchanges an authenticated session at one party for a trusted assertion at another, so credentials are presented once and held in one place." },
      { id: "c-authorisation-server-and-token-service", sourceId: "authorisation-server-and-token-service", layerId: "l-identity-and-access", icon: "key", name: "Authorisation Server & Token Service", description: "Issues, refreshes, exchanges and revokes the tokens that carry identity and scope between parties. Where OAuth grant flows are implemented." },
      { id: "c-multi-factor-and-step-up-authentication", sourceId: "multi-factor-and-step-up-authentication", layerId: "l-identity-and-access", icon: "fingerprint", name: "Multi-Factor & Step-Up Authentication", description: "Requires additional proof, either at sign-in or at the point a sensitive action is attempted, rather than trusting the original session indefinitely." },
      { id: "c-privileged-access-management", sourceId: "privileged-access-management", layerId: "l-identity-and-access", icon: "shield", name: "Privileged Access Management", description: "Brokers, time-bounds and records administrative access, including the break-glass path used when normal controls are unavailable." },
      { id: "c-workload-and-machine-identity", sourceId: "workload-and-machine-identity", layerId: "l-identity-and-access", icon: "bot", name: "Workload & Machine Identity", description: "Gives services their own cryptographic identity so service-to-service calls are authenticated rather than assumed." },
      { id: "c-entitlement-and-policy-models", sourceId: "entitlement-and-policy-models", layerId: "l-identity-and-access", icon: "check-circle", name: "Entitlement & Policy Models", description: "The models by which permission is decided — roles, attributes, or relationships — and the store that holds them." },
      { id: "c-trust-domain-model", sourceId: "trust-domain-model", layerId: "l-identity-and-access", icon: "boxes", name: "Trust Domain Model", description: "Names the trust boundaries policy is written against — which systems share a common trust level, policy and risk appetite, and on what terms one domain accepts assertions from another. The logical model that segmentation and federation physically enforce." },
      { id: "c-session-and-credential-lifecycle", sourceId: "session-and-credential-lifecycle", layerId: "l-identity-and-access", icon: "calendar", name: "Session & Credential Lifecycle", description: "Governs the time dimension of access: enrolment, session lifetime, token TTL, how often a live session is re-evaluated, credential rotation and deprovisioning. Zero Trust claims continuous evaluation; this is the component that makes the claim concrete." },
      { id: "c-device-identity-and-enrolment", sourceId: "device-identity-and-enrolment", layerId: "l-endpoint-and-device-trust", icon: "monitor", name: "Device Identity & Enrolment", description: "Registers devices, issues device certificates, and distinguishes managed from unmanaged hardware." },
      { id: "c-configuration-and-hardening-baselines", sourceId: "configuration-and-hardening-baselines", layerId: "l-endpoint-and-device-trust", icon: "settings", name: "Configuration & Hardening Baselines", description: "Enforces a known-good configuration and detects drift away from it." },
      { id: "c-endpoint-detection-and-response-edr", sourceId: "endpoint-detection-and-response-edr", layerId: "l-endpoint-and-device-trust", icon: "monitor", name: "Endpoint Detection & Response (EDR)", description: "Detects malicious behaviour on the device itself and provides the containment capability to isolate it." },
      { id: "c-posture-gated-access", sourceId: "posture-gated-access", layerId: "l-endpoint-and-device-trust", icon: "shield-check", name: "Posture-Gated Access", description: "Publishes device health as a signal to the Policy Engine so access can be conditioned on it." },
      { id: "c-unmanaged-and-byod-containment", sourceId: "unmanaged-and-byod-containment", layerId: "l-endpoint-and-device-trust", icon: "box", name: "Unmanaged & BYOD Containment", description: "Isolates corporate data on devices the organisation does not control, typically by containerisation or browser isolation." },
      { id: "c-zero-trust-network-access-ztna", sourceId: "zero-trust-network-access-ztna", layerId: "l-network-and-infrastructure", icon: "lock", name: "Zero Trust Network Access (ZTNA)", description: "Grants access to individual applications based on identity and posture rather than placing the client on a network. Replaces broad VPN access." },
      { id: "c-micro-segmentation", sourceId: "micro-segmentation", layerId: "l-network-and-infrastructure", icon: "layers", name: "Micro-segmentation", description: "Restricts lateral movement by permitting only the flows that are explicitly required between workloads." },
      { id: "c-edge-protection-waf-and-ddos", sourceId: "edge-protection-waf-and-ddos", layerId: "l-network-and-infrastructure", icon: "shield", name: "Edge Protection (WAF & DDoS)", description: "Filters hostile traffic before it reaches an application — injection attempts, bot traffic, volumetric floods." },
      { id: "c-egress-control", sourceId: "egress-control", layerId: "l-network-and-infrastructure", icon: "upload", name: "Egress Control", description: "Governs what internal systems may reach outbound, constraining both data exfiltration and command-and-control traffic." },
      { id: "c-private-connectivity", sourceId: "private-connectivity", layerId: "l-network-and-infrastructure", icon: "plug", name: "Private Connectivity", description: "Keeps traffic between systems off the public internet entirely." },
      { id: "c-operational-technology-isolation", sourceId: "operational-technology-isolation", layerId: "l-network-and-infrastructure", icon: "cpu", name: "Operational Technology Isolation", description: "Separates industrial and building-control networks, which frequently cannot be patched or authenticated conventionally." },
      { id: "c-static-analysis-sast", sourceId: "static-analysis-sast", layerId: "l-application-and-api", icon: "code", name: "Static Analysis (SAST)", description: "Inspects source code without running it, finding injection flaws, unsafe patterns and hardcoded secrets during development." },
      { id: "c-software-composition-analysis-sca", sourceId: "software-composition-analysis-sca", layerId: "l-application-and-api", icon: "package", name: "Software Composition Analysis (SCA)", description: "Identifies third-party and transitive dependencies and their known vulnerabilities. Produces the component inventory an SBOM is built from." },
      { id: "c-dynamic-analysis-dast", sourceId: "dynamic-analysis-dast", layerId: "l-application-and-api", icon: "search", name: "Dynamic Analysis (DAST)", description: "Exercises a running application to find issues only visible at runtime — authentication defects, misconfiguration, broken access control." },
      { id: "c-secrets-management", sourceId: "secrets-management", layerId: "l-application-and-api", icon: "key", name: "Secrets Management", description: "Stores, issues, rotates and audits credentials so they never live in source, configuration or images." },
      { id: "c-container-and-image-assurance", sourceId: "container-and-image-assurance", layerId: "l-application-and-api", icon: "box", name: "Container & Image Assurance", description: "Scans images for vulnerable packages and blocks non-compliant or unsigned artefacts at deployment." },
      { id: "c-api-threat-protection", sourceId: "api-threat-protection", layerId: "l-application-and-api", icon: "plug", name: "API Threat Protection", description: "Applies schema validation, authentication, rate limiting and abuse detection at the API edge, addressing the OWASP API risks." },
      { id: "c-runtime-application-protection", sourceId: "runtime-application-protection", layerId: "l-application-and-api", icon: "activity", name: "Runtime Application Protection", description: "Detects and blocks exploitation of a running workload, including behaviour never seen in testing." },
      { id: "c-classification-and-discovery", sourceId: "classification-and-discovery", layerId: "l-data-protection", icon: "tag", name: "Classification & Discovery", description: "Finds sensitive data and labels it, producing the metadata every other data control depends on." },
      { id: "c-encryption-and-key-management", sourceId: "encryption-and-key-management", layerId: "l-data-protection", icon: "lock", name: "Encryption & Key Management", description: "Encrypts data at rest and in transit, and governs the keys — including customer-managed and hold-your-own-key arrangements." },
      { id: "c-masking-and-tokenisation", sourceId: "masking-and-tokenisation", layerId: "l-data-protection", icon: "eye", name: "Masking & Tokenisation", description: "Substitutes sensitive values with masked or surrogate equivalents. Masking is a presentation control applied at query time; tokenisation replaces the value at rest." },
      { id: "c-data-loss-prevention", sourceId: "data-loss-prevention", layerId: "l-data-protection", icon: "shield", name: "Data Loss Prevention", description: "Inspects data in motion and at rest for policy violations and blocks or quarantines egress." },
      { id: "c-rights-and-access-governance", sourceId: "rights-and-access-governance", layerId: "l-data-protection", icon: "user", name: "Rights & Access Governance", description: "Reviews and certifies who holds access to which data over time, closing the gap between access granted and access still warranted." },
      { id: "c-content-and-malware-inspection", sourceId: "content-and-malware-inspection", layerId: "l-data-protection", icon: "search", name: "Content & Malware Inspection", description: "Scans files entering the organisation — uploads, attachments, partner transfers — before they reach a trusted store." },
      { id: "c-posture-management-cspm", sourceId: "posture-management-cspm", layerId: "l-cloud-platform", icon: "gauge", name: "Posture Management (CSPM)", description: "Continuously evaluates cloud configuration against benchmarks and flags drift and exposure." },
      { id: "c-cloud-entitlement-management-ciem", sourceId: "cloud-entitlement-management-ciem", layerId: "l-cloud-platform", icon: "key", name: "Cloud Entitlement Management (CIEM)", description: "Analyses effective cloud permissions — usually far broader than intended — and drives them toward least privilege." },
      { id: "c-infrastructure-as-code-assurance", sourceId: "infrastructure-as-code-assurance", layerId: "l-cloud-platform", icon: "code", name: "Infrastructure-as-Code Assurance", description: "Evaluates infrastructure definitions before provisioning, so misconfiguration is prevented rather than detected." },
      { id: "c-secure-landing-zone", sourceId: "secure-landing-zone", layerId: "l-cloud-platform", icon: "layers", name: "Secure Landing Zone", description: "Provides accounts, networks and guardrails that are compliant by default, so teams inherit controls rather than implementing them." },
      { id: "c-workload-protection-cwpp", sourceId: "workload-protection-cwpp", layerId: "l-cloud-platform", icon: "server", name: "Workload Protection (CWPP)", description: "Protects running compute — VMs, containers, serverless — with vulnerability and runtime threat detection." },
      { id: "c-model-and-use-case-approval", sourceId: "model-and-use-case-approval", layerId: "l-ai-and-autonomous-agents", icon: "check-circle", name: "Model & Use-Case Approval", description: "Governs which models may be used for what, with review proportionate to the risk of the use case." },
      { id: "c-prompt-and-content-filtering", sourceId: "prompt-and-content-filtering", layerId: "l-ai-and-autonomous-agents", icon: "filter", name: "Prompt & Content Filtering", description: "Inspects inputs and outputs for injection attempts, sensitive data disclosure and unsafe content." },
      { id: "c-retrieval-access-control", sourceId: "retrieval-access-control", layerId: "l-ai-and-autonomous-agents", icon: "search", name: "Retrieval Access Control", description: "Ensures retrieval-augmented systems only surface content the requesting user is entitled to see — the most common way an AI feature leaks data." },
      { id: "c-agent-containment", sourceId: "agent-containment", layerId: "l-ai-and-autonomous-agents", icon: "bot", name: "Agent Containment", description: "Bounds what an autonomous agent may do: tool allow-lists, spend and action limits, human approval for consequential steps." },
      { id: "c-ai-supply-chain-assurance", sourceId: "ai-supply-chain-assurance", layerId: "l-ai-and-autonomous-agents", icon: "package", name: "AI Supply Chain Assurance", description: "Verifies provenance of models, weights and datasets, treating them as dependencies with the same scrutiny as libraries." },
      { id: "c-ai-observability-and-audit", sourceId: "ai-observability-and-audit", layerId: "l-ai-and-autonomous-agents", icon: "file", name: "AI Observability & Audit", description: "Records prompts, retrieved context, tool invocations and outputs so behaviour can be investigated after the fact." },
      { id: "c-policy-and-standards", sourceId: "policy-and-standards", layerId: "l-governance-risk-and-compliance", icon: "book-open", name: "Policy & Standards", description: "The documented rules control decisions are judged against, and the exception process for departing from them deliberately rather than silently." },
      { id: "c-risk-management", sourceId: "risk-management", layerId: "l-governance-risk-and-compliance", icon: "trending-up", name: "Risk Management", description: "Identifies, quantifies and tracks risk so investment follows evidence rather than intuition." },
      { id: "c-control-catalogue-and-framework-mapping", sourceId: "control-catalogue-and-framework-mapping", layerId: "l-governance-risk-and-compliance", icon: "table", name: "Control Catalogue & Framework Mapping", description: "Maps implemented controls to the frameworks the organisation is measured against, so one control satisfies many obligations." },
      { id: "c-compliance-evidence-and-audit-readiness", sourceId: "compliance-evidence-and-audit-readiness", layerId: "l-governance-risk-and-compliance", icon: "file", name: "Compliance Evidence & Audit Readiness", description: "Collects proof continuously rather than assembling it under audit pressure." },
      { id: "c-security-awareness-and-phishing-simulation", sourceId: "security-awareness-and-phishing-simulation", layerId: "l-people-and-insider-risk", icon: "book-open", name: "Security Awareness & Phishing Simulation", description: "Builds and measures the ability to recognise social engineering." },
      { id: "c-insider-risk-detection", sourceId: "insider-risk-detection", layerId: "l-people-and-insider-risk", icon: "user", name: "Insider Risk Detection", description: "Correlates behavioural signals to surface misuse of legitimate access, which no perimeter control will catch." },
      { id: "c-joiner-mover-leaver-automation", sourceId: "joiner-mover-leaver-automation", layerId: "l-people-and-insider-risk", icon: "users", name: "Joiner–Mover–Leaver Automation", description: "Ensures access is granted, adjusted and — critically — removed as people move, rather than accumulating." },
      { id: "c-collaboration-and-sharing-controls", sourceId: "collaboration-and-sharing-controls", layerId: "l-people-and-insider-risk", icon: "share-2", name: "Collaboration & Sharing Controls", description: "Governs external sharing in the tools people actually work in." },
      { id: "c-vendor-assessment-and-tiering", sourceId: "vendor-assessment-and-tiering", layerId: "l-supply-chain-and-third-party-risk", icon: "briefcase", name: "Vendor Assessment & Tiering", description: "Assesses suppliers proportionate to the access and data they hold, and re-assesses as that changes." },
      { id: "c-software-bill-of-materials-sbom", sourceId: "software-bill-of-materials-sbom", layerId: "l-supply-chain-and-third-party-risk", icon: "boxes", name: "Software Bill of Materials (SBOM)", description: "Maintains a component inventory for what is built and consumed, so exposure to a new vulnerability is a query rather than an investigation." },
      { id: "c-build-provenance-and-artefact-signing", sourceId: "build-provenance-and-artefact-signing", layerId: "l-supply-chain-and-third-party-risk", icon: "file", name: "Build Provenance & Artefact Signing", description: "Proves an artefact was built from the expected source by the expected pipeline." },
      { id: "c-third-party-access-control", sourceId: "third-party-access-control", layerId: "l-supply-chain-and-third-party-risk", icon: "link", name: "Third-Party Access Control", description: "Grants partners and contractors time-bounded, scoped access rather than standing credentials." },
      { id: "c-log-ingestion-and-siem", sourceId: "log-ingestion-and-siem", layerId: "l-detection-and-security-operations", icon: "database", name: "Log Ingestion & SIEM", description: "Centralises security-relevant telemetry and correlates it into detections. Architecturally an ingestion pipeline with a security purpose." },
      { id: "c-detection-engineering", sourceId: "detection-engineering", layerId: "l-detection-and-security-operations", icon: "git-branch", name: "Detection Engineering", description: "Treats detections as versioned, tested code mapped to adversary behaviour rather than as tuning done in a console." },
      { id: "c-threat-intelligence", sourceId: "threat-intelligence", layerId: "l-detection-and-security-operations", icon: "globe", name: "Threat Intelligence", description: "Supplies external context on adversaries and indicators, feeding both detection and the Policy Engine." },
      { id: "c-vulnerability-and-exposure-management", sourceId: "vulnerability-and-exposure-management", layerId: "l-detection-and-security-operations", icon: "search", name: "Vulnerability & Exposure Management", description: "Finds, prioritises and tracks remediation of weaknesses by real exploitability rather than raw severity." },
      { id: "c-control-validation", sourceId: "control-validation", layerId: "l-detection-and-security-operations", icon: "sparkles", name: "Control Validation", description: "Tests whether controls actually work, rather than assuming deployment equals effectiveness." },
      { id: "c-tamper-evident-audit-trail", sourceId: "tamper-evident-audit-trail", layerId: "l-detection-and-security-operations", icon: "calendar", name: "Tamper-Evident Audit Trail", description: "Records security-relevant actions in a form that resists alteration, including by administrators." },
      { id: "c-incident-response", sourceId: "incident-response", layerId: "l-response-continuity-and-recovery", icon: "bell", name: "Incident Response", description: "Defined playbooks, roles and authority to act — decided in advance, not during the incident." },
      { id: "c-response-automation-soar", sourceId: "response-automation-soar", layerId: "l-response-continuity-and-recovery", icon: "zap", name: "Response Automation (SOAR)", description: "Executes containment steps at machine speed: isolate host, revoke session, block indicator." },
      { id: "c-crisis-communication", sourceId: "crisis-communication", layerId: "l-response-continuity-and-recovery", icon: "bell", name: "Crisis Communication", description: "Coordinates legal, regulatory and customer communication under statutory notification deadlines." },
      { id: "c-immutable-backup", sourceId: "immutable-backup", layerId: "l-response-continuity-and-recovery", icon: "database", name: "Immutable Backup", description: "Maintains restore points that ransomware cannot encrypt or delete, including from a compromised admin account." },
      { id: "c-recovery-assurance", sourceId: "recovery-assurance", layerId: "l-response-continuity-and-recovery", icon: "refresh-cw", name: "Recovery Assurance", description: "Proves recovery works by testing it, rather than discovering the gap during an incident." },
      { id: "c-post-incident-learning", sourceId: "post-incident-learning", layerId: "l-response-continuity-and-recovery", icon: "lightbulb", name: "Post-Incident Learning", description: "Converts incidents into control improvements through blameless review." }
    ],
    products: [
      { id: "sp-entra-id", icon: "key", name: "Microsoft Entra ID", vendor: "Microsoft", statusId: "strategic", notes: "Target identity provider: SSO, MFA and Conditional Access for workforce identities." },
      { id: "sp-active-directory", icon: "server", name: "Active Directory", vendor: "Microsoft", statusId: "contain", notes: "Retained for legacy on-premises applications; synchronised to Entra ID. No new dependencies." },
      { id: "sp-okta", icon: "key", name: "Okta Workforce Identity", vendor: "Okta", statusId: "decommission", notes: "Inherited from an acquisition; users migrating to Entra ID." },
      { id: "sp-cyberark", icon: "lock", name: "CyberArk Privileged Access", vendor: "CyberArk", statusId: "strategic", notes: "Brokers and records all administrative sessions, including break-glass." },
      { id: "sp-vault", icon: "key", name: "HashiCorp Vault", vendor: "HashiCorp", statusId: "strategic", notes: "Secrets, dynamic credentials and workload encryption for platform teams." },
      { id: "sp-intune", icon: "monitor", name: "Microsoft Intune", vendor: "Microsoft", statusId: "strategic", notes: "Device enrolment, compliance baselines and posture signals for Conditional Access." },
      { id: "sp-crowdstrike", icon: "shield", name: "CrowdStrike Falcon", vendor: "CrowdStrike", statusId: "strategic", notes: "EDR on all managed endpoints and servers." },
      { id: "sp-zscaler-zpa", icon: "lock", name: "Zscaler Private Access", vendor: "Zscaler", statusId: "emerging", notes: "ZTNA pilot for private applications, replacing broad VPN access." },
      { id: "sp-remote-vpn", icon: "network", name: "Remote-access VPN", vendor: "Various", statusId: "decommission", notes: "Being replaced by ZTNA application by application." },
      { id: "sp-cloudflare", icon: "cloud", name: "Cloudflare WAF & DDoS", vendor: "Cloudflare", statusId: "strategic", notes: "Edge protection for all internet-facing applications and APIs." },
      { id: "sp-wiz", icon: "gauge", name: "Wiz", vendor: "Wiz", statusId: "strategic", notes: "Cloud posture, entitlement and workload protection across all cloud accounts." },
      { id: "sp-semgrep", icon: "code", name: "Semgrep", vendor: "Semgrep", statusId: "emerging", notes: "Static analysis in pull requests; rolling out team by team." },
      { id: "sp-snyk", icon: "package", name: "Snyk", vendor: "Snyk", statusId: "tactical", notes: "Dependency and container scanning; consolidation with other scanners under review." },
      { id: "sp-sentinel", icon: "search", name: "Microsoft Sentinel", vendor: "Microsoft", statusId: "strategic", notes: "Target SIEM and automated response playbooks." },
      { id: "sp-splunk-es", icon: "search", name: "Splunk Enterprise Security", vendor: "Splunk", statusId: "contain", notes: "Legacy SIEM; no new data sources while detections migrate to Sentinel." },
      { id: "sp-purview", icon: "shield-check", name: "Microsoft Purview", vendor: "Microsoft", statusId: "strategic", notes: "Data classification, DLP, insider risk and collaboration controls." },
      { id: "sp-veeam", icon: "database", name: "Veeam with immutable repositories", vendor: "Veeam", statusId: "strategic", notes: "Backups with object-lock immutability for ransomware recovery." },
      { id: "sp-knowbe4", icon: "book-open", name: "KnowBe4", vendor: "KnowBe4", statusId: "tactical", notes: "Security awareness training and phishing simulation." }
    ],
    transitions: [],
    mappings: {
      userUseCases: [
        {userId: "su-ciso",useCaseId: "suc-demonstrate-compliance"},
        {userId: "su-ciso",useCaseId: "suc-ransomware-recovery"},
        {userId: "su-ciso",useCaseId: "suc-detect-respond"},
        {userId: "su-ciso",useCaseId: "suc-adopt-ai-safely"},
        {userId: "su-security-architect",useCaseId: "suc-zero-trust-access"},
        {userId: "su-security-architect",useCaseId: "suc-protect-sensitive-data"},
        {userId: "su-security-architect",useCaseId: "suc-secure-delivery"},
        {userId: "su-security-architect",useCaseId: "suc-adopt-ai-safely"},
        {userId: "su-soc-analyst",useCaseId: "suc-detect-respond"},
        {userId: "su-soc-analyst",useCaseId: "suc-ransomware-recovery"},
        {userId: "su-platform-engineer",useCaseId: "suc-privileged-access"},
        {userId: "su-platform-engineer",useCaseId: "suc-secure-delivery"},
        {userId: "su-platform-engineer",useCaseId: "suc-zero-trust-access"},
        {userId: "su-developer",useCaseId: "suc-secure-delivery"},
        {userId: "su-developer",useCaseId: "suc-adopt-ai-safely"},
        {userId: "su-risk-compliance",useCaseId: "suc-demonstrate-compliance"},
        {userId: "su-risk-compliance",useCaseId: "suc-protect-sensitive-data"},
        {userId: "su-risk-compliance",useCaseId: "suc-third-party-risk"},
        {userId: "su-workforce",useCaseId: "suc-zero-trust-access"},
        {userId: "su-supplier",useCaseId: "suc-third-party-risk"}
      ],
      useCaseComponents: [
        {useCaseId: "suc-zero-trust-access",componentId: "c-policy-engine-pe"},
        {useCaseId: "suc-zero-trust-access",componentId: "c-policy-administrator-pa"},
        {useCaseId: "suc-zero-trust-access",componentId: "c-policy-enforcement-point-pep"},
        {useCaseId: "suc-zero-trust-access",componentId: "c-trust-signal-sources"},
        {useCaseId: "suc-zero-trust-access",componentId: "c-federation-and-single-sign-on"},
        {useCaseId: "suc-zero-trust-access",componentId: "c-multi-factor-and-step-up-authentication"},
        {useCaseId: "suc-zero-trust-access",componentId: "c-session-and-credential-lifecycle"},
        {useCaseId: "suc-zero-trust-access",componentId: "c-posture-gated-access"},
        {useCaseId: "suc-zero-trust-access",componentId: "c-zero-trust-network-access-ztna"},
        {useCaseId: "suc-privileged-access",componentId: "c-privileged-access-management"},
        {useCaseId: "suc-privileged-access",componentId: "c-directory-services"},
        {useCaseId: "suc-privileged-access",componentId: "c-session-and-credential-lifecycle"},
        {useCaseId: "suc-privileged-access",componentId: "c-tamper-evident-audit-trail"},
        {useCaseId: "suc-secure-delivery",componentId: "c-static-analysis-sast"},
        {useCaseId: "suc-secure-delivery",componentId: "c-software-composition-analysis-sca"},
        {useCaseId: "suc-secure-delivery",componentId: "c-dynamic-analysis-dast"},
        {useCaseId: "suc-secure-delivery",componentId: "c-secrets-management"},
        {useCaseId: "suc-secure-delivery",componentId: "c-container-and-image-assurance"},
        {useCaseId: "suc-secure-delivery",componentId: "c-infrastructure-as-code-assurance"},
        {useCaseId: "suc-secure-delivery",componentId: "c-software-bill-of-materials-sbom"},
        {useCaseId: "suc-secure-delivery",componentId: "c-build-provenance-and-artefact-signing"},
        {useCaseId: "suc-protect-sensitive-data",componentId: "c-classification-and-discovery"},
        {useCaseId: "suc-protect-sensitive-data",componentId: "c-encryption-and-key-management"},
        {useCaseId: "suc-protect-sensitive-data",componentId: "c-masking-and-tokenisation"},
        {useCaseId: "suc-protect-sensitive-data",componentId: "c-data-loss-prevention"},
        {useCaseId: "suc-protect-sensitive-data",componentId: "c-rights-and-access-governance"},
        {useCaseId: "suc-detect-respond",componentId: "c-log-ingestion-and-siem"},
        {useCaseId: "suc-detect-respond",componentId: "c-detection-engineering"},
        {useCaseId: "suc-detect-respond",componentId: "c-threat-intelligence"},
        {useCaseId: "suc-detect-respond",componentId: "c-endpoint-detection-and-response-edr"},
        {useCaseId: "suc-detect-respond",componentId: "c-incident-response"},
        {useCaseId: "suc-detect-respond",componentId: "c-response-automation-soar"},
        {useCaseId: "suc-ransomware-recovery",componentId: "c-immutable-backup"},
        {useCaseId: "suc-ransomware-recovery",componentId: "c-recovery-assurance"},
        {useCaseId: "suc-ransomware-recovery",componentId: "c-incident-response"},
        {useCaseId: "suc-ransomware-recovery",componentId: "c-crisis-communication"},
        {useCaseId: "suc-ransomware-recovery",componentId: "c-post-incident-learning"},
        {useCaseId: "suc-adopt-ai-safely",componentId: "c-model-and-use-case-approval"},
        {useCaseId: "suc-adopt-ai-safely",componentId: "c-prompt-and-content-filtering"},
        {useCaseId: "suc-adopt-ai-safely",componentId: "c-retrieval-access-control"},
        {useCaseId: "suc-adopt-ai-safely",componentId: "c-agent-containment"},
        {useCaseId: "suc-adopt-ai-safely",componentId: "c-ai-observability-and-audit"},
        {useCaseId: "suc-demonstrate-compliance",componentId: "c-policy-and-standards"},
        {useCaseId: "suc-demonstrate-compliance",componentId: "c-control-catalogue-and-framework-mapping"},
        {useCaseId: "suc-demonstrate-compliance",componentId: "c-compliance-evidence-and-audit-readiness"},
        {useCaseId: "suc-demonstrate-compliance",componentId: "c-control-validation"},
        {useCaseId: "suc-demonstrate-compliance",componentId: "c-vulnerability-and-exposure-management"},
        {useCaseId: "suc-demonstrate-compliance",componentId: "c-posture-management-cspm"},
        {useCaseId: "suc-third-party-risk",componentId: "c-vendor-assessment-and-tiering"},
        {useCaseId: "suc-third-party-risk",componentId: "c-third-party-access-control"},
        {useCaseId: "suc-third-party-risk",componentId: "c-software-bill-of-materials-sbom"},
        {useCaseId: "suc-third-party-risk",componentId: "c-build-provenance-and-artefact-signing"}
      ],
      componentProducts: [
        {componentId: "c-directory-services",productId: "sp-entra-id"},
        {componentId: "c-directory-services",productId: "sp-active-directory"},
        {componentId: "c-directory-services",productId: "sp-okta"},
        {componentId: "c-federation-and-single-sign-on",productId: "sp-entra-id"},
        {componentId: "c-federation-and-single-sign-on",productId: "sp-okta"},
        {componentId: "c-authorisation-server-and-token-service",productId: "sp-entra-id"},
        {componentId: "c-multi-factor-and-step-up-authentication",productId: "sp-entra-id"},
        {componentId: "c-policy-engine-pe",productId: "sp-entra-id"},
        {componentId: "c-privileged-access-management",productId: "sp-cyberark"},
        {componentId: "c-secrets-management",productId: "sp-vault"},
        {componentId: "c-workload-and-machine-identity",productId: "sp-vault"},
        {componentId: "c-encryption-and-key-management",productId: "sp-vault"},
        {componentId: "c-device-identity-and-enrolment",productId: "sp-intune"},
        {componentId: "c-configuration-and-hardening-baselines",productId: "sp-intune"},
        {componentId: "c-posture-gated-access",productId: "sp-intune"},
        {componentId: "c-endpoint-detection-and-response-edr",productId: "sp-crowdstrike"},
        {componentId: "c-zero-trust-network-access-ztna",productId: "sp-zscaler-zpa"},
        {componentId: "c-zero-trust-network-access-ztna",productId: "sp-remote-vpn"},
        {componentId: "c-policy-enforcement-point-pep",productId: "sp-zscaler-zpa"},
        {componentId: "c-edge-protection-waf-and-ddos",productId: "sp-cloudflare"},
        {componentId: "c-posture-management-cspm",productId: "sp-wiz"},
        {componentId: "c-cloud-entitlement-management-ciem",productId: "sp-wiz"},
        {componentId: "c-workload-protection-cwpp",productId: "sp-wiz"},
        {componentId: "c-static-analysis-sast",productId: "sp-semgrep"},
        {componentId: "c-software-composition-analysis-sca",productId: "sp-snyk"},
        {componentId: "c-container-and-image-assurance",productId: "sp-snyk"},
        {componentId: "c-log-ingestion-and-siem",productId: "sp-sentinel"},
        {componentId: "c-log-ingestion-and-siem",productId: "sp-splunk-es"},
        {componentId: "c-response-automation-soar",productId: "sp-sentinel"},
        {componentId: "c-classification-and-discovery",productId: "sp-purview"},
        {componentId: "c-data-loss-prevention",productId: "sp-purview"},
        {componentId: "c-insider-risk-detection",productId: "sp-purview"},
        {componentId: "c-collaboration-and-sharing-controls",productId: "sp-purview"},
        {componentId: "c-immutable-backup",productId: "sp-veeam"},
        {componentId: "c-security-awareness-and-phishing-simulation",productId: "sp-knowbe4"}
      ]
    }
  }
});
